### ISSUE TITLE
in index/password/email/ replace 'userEmail.json' by 'podName$userEmail.json

### ISSUE THREAD

**Issue by bourgeoa** [solid-contrib/pivot#48]
in index/password/email/ by replacing 'userEmail.json' by 'podName$userEmail.json this would allow to use one email for multiple pods.

Why ?
- agent can be understood as one email
- CSS allow multiple accounts for one pod
- in NSS owners is defined by using the multiple accounts to the same pod
- actually an email is unique through all the server and cannot be reused on different pods
- an agent/email may have multiple pods and will need multiple emails, which is bad practice and do not allow to update lost password

The proposal
- avoid the use of fake emails
- allow one email to be used on multiple pods

**Comment by michielbdejong** [comment]
I don't think I fully understand the ask.

I think CSS allows both one-to-one and one-to-many mappings from email address(es) to pod(s), but not many-to-one or many-to-many. If this is a generic feature request I'm hesitant to implement something like this at the Pivot level, since it's clearly something the CSS team thought through thoroughly.

If it's something that somehow blocks the solidcommunity.net migration then I would be more inclined to consider implementing some sort of work-around to let Pivot diverge from upstream CSS on this, but in all cases, I would like to see a feature request to CSS first, and only if that is declined, a feature request to Pivot.

Could you submit this request to CSS, or did you already do so?

**Comment by bourgeoa** [comment]
I think I did not fully understood the actual possibilities of managing accounts in CSS.
I succeeded to create multiple pods to one account, which was my main concern

I shall experiment the other possibilities.
